version: '3.9'
volumes:
  database-volume: null
  pgadmin: null
networks:
  backend:
    external:
      name: backend
services:
  database-admin:
    image: "dpage/pgadmin4:4.24"
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
      PGADMIN_LISTEN_PORT: 80
    ports:
      - $PGADMIN_HTTP_PORT:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - database
    networks:
      - backend
  database:
    image: postgres:latest
    volumes:
      - database-volume:/var/lib/postgresql/data
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
    restart: always
    ports:
      - $POSTGRES_EXPOSED_PORT:5432
    networks:
      - backend
